### ISSUE TITLE
Plugin throws exception blocking pulls/clones

### ISSUE THREAD

**Issue by bocon13** [LucaPrete/gerrit-counter#3]
[2015-03-16 09:26:48,050] WARN  / : Internal error during upload-pack
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
	at org.eclipse.jetty.util.SharedBlockingCallback$Blocker.block(SharedBlockingCallback.java:216)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:128)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:370)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.eclipse.jgit.util.TemporaryBuffer.write(TemporaryBuffer.java:138)
	at org.eclipse.jgit.transport.SideBandOutputStream.writeBuffer(SideBandOutputStream.java:171)
	at org.eclipse.jgit.transport.SideBandOutputStream.write(SideBandOutputStream.java:151)
	at org.eclipse.jgit.internal.storage.pack.PackOutputStream.write(PackOutputStream.java:126)
	at org.eclipse.jgit.internal.storage.file.PackFile.copyAsIs2(PackFile.java:519)
	at org.eclipse.jgit.internal.storage.file.PackFile.copyAsIs(PackFile.java:357)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.copyObjectAsIs(WindowCursor.java:190)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeObjectImpl(PackWriter.java:1515)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeBase(PackWriter.java:1557)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeObjectImpl(PackWriter.java:1508)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeObject(PackWriter.java:1492)
	at org.eclipse.jgit.internal.storage.pack.PackOutputStream.writeObject(PackOutputStream.java:164)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.writeObjects(WindowCursor.java:196)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeObjects(PackWriter.java:1480)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writeObjects(PackWriter.java:1468)
	at org.eclipse.jgit.internal.storage.pack.PackWriter.writePack(PackWriter.java:1036)
	at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1417)
	at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1271)
	at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:717)
	at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:628)
	at org.eclipse.jgit.http.server.UploadPackServlet.doPost(UploadPackServlet.java:187)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:237)
	at com.google.gerrit.httpd.GitOverHttpServlet$UploadFilter.doFilter(GitOverHttpServlet.java:253)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
	at org.eclipse.jgit.http.server.UploadPackServlet$Factory.doFilter(UploadPackServlet.java:145)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
	at org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:151)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
	at org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:80)
	at org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:235)
	at org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:215)
	at org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:101)
	at org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:175)
	at org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:133)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:279)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:269)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:113)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequireSslFilter.doFilter(RequireSslFilter.java:68)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.ProjectDigestFilter.doFilter(ProjectDigestFilter.java:107)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:64)
	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:57)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.gerrit.pgm.http.jetty.ProjectQoSFilter.doFilter(ProjectQoSFilter.java:132)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:219)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
	at org.eclipse.jetty.server.Server.handleAsync(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:291)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:241)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:154)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	... 1 more
[2015-03-16 10:11:16,659] ERROR com.googlesource.gerrit.plugins.gerritcounter.DBConnection : ERROR: null value in column "clones" violates not-null constraint
  Detail: Failing row contains (2015-03-16, null, spring-open, 1).

**Comment by LucaPrete** [comment]
Fixed with patch ce2eca7f3f on March 24th.
